"""redesign admissions table

Revision ID: 69fba9df922f
Revises: 
Create Date: 2026-06-09 14:57:47.089972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69fba9df922f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('institute_id', sa.Integer(), nullable=False))
    op.add_column('admissions', sa.Column('candidate_name', sa.String(), nullable=False))
    op.add_column('admissions', sa.Column('parent_name', sa.String(), nullable=False))
    op.add_column('admissions', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('admissions', sa.Column('class_id', sa.Integer(), nullable=False))
    op.add_column('admissions', sa.Column('visit_date', sa.Date(), nullable=False))
    op.add_column('admissions', sa.Column('converted_student_id', sa.Integer(), nullable=True))
    op.add_column('admissions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('admissions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='admissionstatus'),
               type_=sa.String(length=20),
               nullable=False)
    op.create_index('ix_admissions_institute_deleted', 'admissions', ['institute_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_admissions_institute_id'), 'admissions', ['institute_id'], unique=False)
    op.create_index('ix_admissions_institute_status', 'admissions', ['institute_id', 'status'], unique=False)
    op.drop_constraint(op.f('admissions_student_id_fkey'), 'admissions', type_='foreignkey')
    op.create_foreign_key(None, 'admissions', 'students', ['converted_student_id'], ['id'])
    op.create_foreign_key(None, 'admissions', 'institutes', ['institute_id'], ['id'])
    op.create_foreign_key(None, 'admissions', 'classes', ['class_id'], ['id'])
    op.drop_column('admissions', 'remarks')
    op.drop_column('admissions', 'student_id')
    op.drop_column('admissions', 'applied_date')
    op.create_index(op.f('ix_fee_plans_is_deleted'), 'fee_plans', ['is_deleted'], unique=False)
    op.create_index('ix_installments_plan_deleted', 'installments', ['fee_plan_id', 'is_deleted'], unique=False)
    op.alter_column('institutes', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_subjects_class_deleted', 'subjects', ['class_id', 'is_deleted'], unique=False)
    op.create_index('ix_test_scores_test_deleted', 'test_scores', ['test_id', 'is_deleted'], unique=False)
    op.create_index('ix_users_institute_deleted', 'users', ['institute_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_institute_deleted', table_name='users')
    op.drop_index('ix_test_scores_test_deleted', table_name='test_scores')
    op.drop_index('ix_subjects_class_deleted', table_name='subjects')
    op.alter_column('institutes', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_installments_plan_deleted', table_name='installments')
    op.drop_index(op.f('ix_fee_plans_is_deleted'), table_name='fee_plans')
    op.add_column('admissions', sa.Column('applied_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('admissions', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('admissions', sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.drop_constraint(None, 'admissions', type_='foreignkey')
    op.create_foreign_key(op.f('admissions_student_id_fkey'), 'admissions', 'students', ['student_id'], ['id'])
    op.drop_index('ix_admissions_institute_status', table_name='admissions')
    op.drop_index(op.f('ix_admissions_institute_id'), table_name='admissions')
    op.drop_index('ix_admissions_institute_deleted', table_name='admissions')
    op.alter_column('admissions', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='admissionstatus'),
               nullable=True)
    op.drop_column('admissions', 'created_at')
    op.drop_column('admissions', 'converted_student_id')
    op.drop_column('admissions', 'visit_date')
    op.drop_column('admissions', 'class_id')
    op.drop_column('admissions', 'phone')
    op.drop_column('admissions', 'parent_name')
    op.drop_column('admissions', 'candidate_name')
    op.drop_column('admissions', 'institute_id')
    # ### end Alembic commands ###
