"""add parent qr feature

Revision ID: 9c6759b481b1
Revises: 6d38f4ee5442
Create Date: 2026-06-19 19:35:19.555102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6759b481b1'
down_revision: Union[str, None] = '6d38f4ee5442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutes', sa.Column('drive_url', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_token', sa.String(length=36), nullable=True))
    op.add_column('students', sa.Column('parent_pin_hash', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_scan_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('students', sa.Column('parent_scan_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('parent_pin_attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_students_parent_token'), 'students', ['parent_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_parent_token'), table_name='students')
    op.drop_column('students', 'parent_pin_attempts')
    op.drop_column('students', 'parent_scan_date')
    op.drop_column('students', 'parent_scan_count')
    op.drop_column('students', 'parent_pin_hash')
    op.drop_column('students', 'parent_token')
    op.drop_column('institutes', 'drive_url')
    # ### end Alembic commands ###
