"""add_last_dashboard_access

Revision ID: bf5af29044d5
Revises: 9c6759b481b1
Create Date: 2026-06-20 23:28:27.698013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5af29044d5'
down_revision: Union[str, None] = '9c6759b481b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutes', sa.Column('last_dashboard_access', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutes', 'last_dashboard_access')
    # ### end Alembic commands ###
