"""add_study_tracker_tables_and_parent_qr_analytics

Revision ID: ae1b44bc41e6
Revises: bf5af29044d5
Create Date: 2026-06-22 23:15:52.203299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1b44bc41e6'
down_revision: Union[str, None] = 'bf5af29044d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('daily_target_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_subjects_id'), 'study_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_study_subjects_user_id'), 'study_subjects', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['study_subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_study_sessions_subject_id'), 'study_sessions', ['subject_id'], unique=False)
    op.create_index('ix_study_sessions_user_ended', 'study_sessions', ['user_id', 'ended_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    # Close any duplicate open sessions before enforcing the unique constraint
    # (keeps the latest started_at open; auto-closes the rest)
    op.execute("""
        UPDATE study_sessions
        SET ended_at = started_at
        WHERE ended_at IS NULL
          AND id NOT IN (
              SELECT DISTINCT ON (user_id) id
              FROM study_sessions
              WHERE ended_at IS NULL
              ORDER BY user_id, started_at DESC
          )
    """)
    # Enforce at most one open session per user at the DB level
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS uq_study_sessions_one_active_per_user
        ON study_sessions (user_id)
        WHERE ended_at IS NULL
    """)
    # columns missed by autogenerate (already existed in local dev DB)
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('students', sa.Column('parent_last_scan_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('students', sa.Column('parent_total_scans', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'parent_total_scans')
    op.drop_column('students', 'parent_last_scan_at')
    op.drop_column('users', 'phone')
    op.execute("DROP INDEX IF EXISTS uq_study_sessions_one_active_per_user")
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index('ix_study_sessions_user_ended', table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_subject_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_study_subjects_user_id'), table_name='study_subjects')
    op.drop_index(op.f('ix_study_subjects_id'), table_name='study_subjects')
    op.drop_table('study_subjects')
    # ### end Alembic commands ###
